### ISSUE TITLE
Add variable room numbers.

### ISSUE THREAD

**Issue by NiteeshK21** [NiteeshK21/HacktoberFest22#6]
Currently, the program has static room numbers and always displays the same room number irrespective of how many people have booked rooms.
Please add a variable for room numbers and also put an option for the user to select a room from all the available rooms.
Any suggestions and solutions posted will be appreciated.

**Comment by RohanTheProgrammer** [comment]
I would like to work on the issue.

**Comment by NiteeshK21** [comment]
> I would like to work on the issue.

You're Welcome! Go ahead.
